name: Greetings

on: [pull_request_target, issues]

permissions: {}

jobs:
  greeting:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/greetings.yml@5e8d0e6d1e76d8577a070db6d0128a91b1c9d5ad # 0.30.2
    permissions:
      contents: read
      issues: write
      pull-requests: write
